import { createContext, useContext, useState } from 'react'

const TRANSLATIONS = {
  en: {
    lang: 'en',
    appName: 'MedGuard AI',
    tagline: 'Clinical Intelligence Platform',
    nav: {
      dashboard: 'Dashboard',
      deidentify: 'De-Identification',
      contradictions: 'Contradictions',
      timeline: 'Timeline',
      reports: 'Reports',
      about: 'About',
    },
    dashboard: {
      title: 'Patient Safety Dashboard',
      subtitle: 'PHI detection · Contradiction monitoring · Clinical risk intelligence',
      docsProcessed: 'Documents Processed',
      phiDetected: 'PHI Detected',
      contradictions: 'Contradictions',
      patients: 'Patients Analyzed',
      riskGauge: 'Avg. Patient Risk',
      recentContradictions: 'Recent Contradictions',
      highRisk: 'High Risk Patients',
      trend: 'Monthly Trend',
      confidence: 'Contradiction Confidence Scores',
      demoNote: 'Demo — Synthea synthetic dataset. No real patient data.',
    },
    deidentify: {
      title: 'PHI De-Identification Engine',
      subtitle: 'Upload a clinical document or paste text. Protected Health Information will be automatically detected and redacted.',
      upload: 'Upload File',
      paste: 'Paste Text',
      analyze: 'Analyze & De-Identify',
      original: 'Original (Contains PHI)',
      redacted: 'De-Identified Document',
      download: 'Download Redacted',
      phiFound: 'PHI Items Found',
      categories: 'PHI Categories',
      privacyRisk: 'Privacy Risk',
    },
    contradictions: {
      title: 'Contradiction Detection Engine',
      subtitle: 'Analyzes clinical documents for allergy conflicts, diagnosis discrepancies, contraindications, and critical lab values.',
      loadDemo: 'Load Demo',
      pasteText: 'Paste Text',
      uploadFiles: 'Upload Files',
      runDemo: 'Run Demo Analysis',
      detected: 'Detected Contradictions',
      riskScore: 'Risk Score',
      riskLevel: 'Risk Level',
      confidence: 'confidence',
      reasoning: 'Show Reasoning Trace',
      hideReasoning: 'Hide Reasoning Trace',
      decisionSupport: 'Clinical Decision Support',
      actions: 'Recommended Actions',
      urgency: 'Urgency',
      alternatives: 'Clinical Note',
    },
    timeline: {
      title: 'Patient Timeline Engine',
      subtitle: 'Reconstructs chronological patient history from clinical documents. Detects temporal contradictions across records.',
      loadDemo: 'Load Demo Timeline',
      upload: 'Upload Documents',
      conflicts: 'Temporal Conflicts',
      events: 'Timeline Events',
      categories: 'Event Categories',
    },
    common: {
      analyzing: 'Analyzing…',
      loading: 'Loading…',
      noData: 'No data loaded',
      error: 'An error occurred',
      demo: 'Demo Mode',
      synthetic: 'Synthetic Synthea data',
      showAll: 'Show All',
      conflict: 'Conflicts Only',
    }
  },
  hi: {
    lang: 'hi',
    appName: 'मेडगार्ड AI',
    tagline: 'क्लिनिकल इंटेलिजेंस प्लेटफॉर्म',
    nav: {
      dashboard: 'डैशबोर्ड',
      deidentify: 'पहचान हटाएं',
      contradictions: 'विरोधाभास',
      timeline: 'टाइमलाइन',
      reports: 'रिपोर्ट',
      about: 'परिचय',
    },
    dashboard: {
      title: 'रोगी सुरक्षा डैशबोर्ड',
      subtitle: 'PHI पहचान · विरोधाभास निगरानी · नैदानिक जोखिम खुफिया जानकारी',
      docsProcessed: 'संसाधित दस्तावेज',
      phiDetected: 'PHI पहचाना गया',
      contradictions: 'विरोधाभास',
      patients: 'विश्लेषित रोगी',
      riskGauge: 'औसत रोगी जोखिम',
      recentContradictions: 'हालिया विरोधाभास',
      highRisk: 'उच्च जोखिम रोगी',
      trend: 'मासिक रुझान',
      confidence: 'विरोधाभास विश्वास स्कोर',
      demoNote: 'डेमो — सिंथेटिक डेटासेट। कोई वास्तविक मरीज डेटा नहीं।',
    },
    deidentify: {
      title: 'PHI पहचान हटाने का इंजन',
      subtitle: 'एक क्लिनिकल दस्तावेज़ अपलोड करें या टेक्स्ट पेस्ट करें। PHI स्वचालित रूप से हटाई जाएगी।',
      upload: 'फ़ाइल अपलोड करें',
      paste: 'टेक्स्ट पेस्ट करें',
      analyze: 'विश्लेषण करें',
      original: 'मूल (PHI के साथ)',
      redacted: 'पहचान-हटाया दस्तावेज़',
      download: 'डाउनलोड करें',
      phiFound: 'PHI मिली',
      categories: 'PHI श्रेणियाँ',
      privacyRisk: 'गोपनीयता जोखिम',
    },
    contradictions: {
      title: 'विरोधाभास पहचान इंजन',
      subtitle: 'एलर्जी संघर्षों, निदान विसंगतियों और महत्वपूर्ण लैब मूल्यों की जांच करता है।',
      loadDemo: 'डेमो लोड करें',
      pasteText: 'टेक्स्ट पेस्ट करें',
      uploadFiles: 'फ़ाइलें अपलोड करें',
      runDemo: 'डेमो विश्लेषण चलाएं',
      detected: 'पहचाने गए विरोधाभास',
      riskScore: 'जोखिम स्कोर',
      riskLevel: 'जोखिम स्तर',
      confidence: 'विश्वास',
      reasoning: 'तर्क दिखाएं',
      hideReasoning: 'तर्क छिपाएं',
      decisionSupport: 'क्लिनिकल निर्णय समर्थन',
      actions: 'अनुशंसित कार्रवाई',
      urgency: 'तात्कालिकता',
      alternatives: 'क्लिनिकल नोट',
    },
    timeline: {
      title: 'रोगी टाइमलाइन इंजन',
      subtitle: 'नैदानिक दस्तावेजों से रोगी इतिहास का कालक्रमिक पुनर्निर्माण।',
      loadDemo: 'डेमो टाइमलाइन लोड करें',
      upload: 'दस्तावेज़ अपलोड करें',
      conflicts: 'समयबद्ध संघर्ष',
      events: 'टाइमलाइन घटनाएं',
      categories: 'घटना श्रेणियाँ',
    },
    common: {
      analyzing: 'विश्लेषण हो रहा है…',
      loading: 'लोड हो रहा है…',
      noData: 'कोई डेटा नहीं',
      error: 'एक त्रुटि हुई',
      demo: 'डेमो मोड',
      synthetic: 'सिंथेटिक डेटा',
      showAll: 'सभी दिखाएं',
      conflict: 'केवल संघर्ष',
    }
  },
  kn: {
    lang: 'kn',
    appName: 'ಮೆಡ್‌ಗಾರ್ಡ್ AI',
    tagline: 'ಕ್ಲಿನಿಕಲ್ ಇಂಟೆಲಿಜೆನ್ಸ್ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್',
    nav: {
      dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      deidentify: 'ಗುರುತು ತೆಗೆ',
      contradictions: 'ವಿರೋಧಾಭಾಸ',
      timeline: 'ಕಾಲಮಾನ',
      reports: 'ವರದಿಗಳು',
      about: 'ಪರಿಚಯ',
    },
    dashboard: {
      title: 'ರೋಗಿ ಸುರಕ್ಷತೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      subtitle: 'PHI ಪರಿಶೋಧನೆ · ವಿರೋಧಾಭಾಸ ಟ್ರ್ಯಾಕಿಂಗ್ · ಕ್ಲಿನಿಕಲ್ ಅಪಾಯ ವಿಶ್ಲೇಷಣೆ',
      docsProcessed: 'ಸಂಸ್ಕರಿಸಿದ ದಾಖಲೆಗಳು',
      phiDetected: 'PHI ಪತ್ತೆ',
      contradictions: 'ವಿರೋಧಾಭಾಸಗಳು',
      patients: 'ವಿಶ್ಲೇಷಿಸಿದ ರೋಗಿಗಳು',
      riskGauge: 'ಸರಾಸರಿ ರೋಗಿ ಅಪಾಯ',
      recentContradictions: 'ಇತ್ತೀಚಿನ ವಿರೋಧಾಭಾಸಗಳು',
      highRisk: 'ಅಧಿಕ ಅಪಾಯದ ರೋಗಿಗಳು',
      trend: 'ಮಾಸಿಕ ಪ್ರವೃತ್ತಿ',
      confidence: 'ವಿರೋಧಾಭಾಸ ವಿಶ್ವಾಸ ಸ್ಕೋರ್',
      demoNote: 'ಡೆಮೊ — ಸಿಂಥೆಟಿಕ್ ಡೇಟಾ. ನೈಜ ರೋಗಿ ಡೇಟಾ ಇಲ್ಲ.',
    },
    deidentify: {
      title: 'PHI ಗುರುತು ತೆಗೆಯುವ ಎಂಜಿನ್',
      subtitle: 'ಕ್ಲಿನಿಕಲ್ ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ಪಠ್ಯ ಅಂಟಿಸಿ. PHI ಸ್ವಯಂಚಾಲಿತವಾಗಿ ತೆಗೆಯಲಾಗುತ್ತದೆ.',
      upload: 'ಫೈಲ್ ಅಪ್‌ಲೋಡ್',
      paste: 'ಪಠ್ಯ ಅಂಟಿಸಿ',
      analyze: 'ವಿಶ್ಲೇಷಿಸಿ',
      original: 'ಮೂಲ (PHI ಸಹಿತ)',
      redacted: 'ಗುರುತು-ತೆಗೆದ ದಾಖಲೆ',
      download: 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      phiFound: 'PHI ಕಂಡು ಬಂದಿದೆ',
      categories: 'PHI ಶ್ರೇಣಿಗಳು',
      privacyRisk: 'ಗೌಪ್ಯತೆ ಅಪಾಯ',
    },
    contradictions: {
      title: 'ವಿರೋಧಾಭಾಸ ಪರಿಶೋಧನಾ ಎಂಜಿನ್',
      subtitle: 'ಔಷಧ ಅಲರ್ಜಿ ಸಂಘರ್ಷಗಳು, ರೋಗನಿರ್ಣಯ ವ್ಯತ್ಯಾಸಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.',
      loadDemo: 'ಡೆಮೊ ಲೋಡ್ ಮಾಡಿ',
      pasteText: 'ಪಠ್ಯ ಅಂಟಿಸಿ',
      uploadFiles: 'ಫೈಲ್‌ಗಳು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      runDemo: 'ಡೆಮೊ ವಿಶ್ಲೇಷಣೆ ಚಲಾಯಿಸಿ',
      detected: 'ಪತ್ತೆ ಹಚ್ಚಿದ ವಿರೋಧಾಭಾಸಗಳು',
      riskScore: 'ಅಪಾಯ ಸ್ಕೋರ್',
      riskLevel: 'ಅಪಾಯ ಮಟ್ಟ',
      confidence: 'ವಿಶ್ವಾಸ',
      reasoning: 'ತರ್ಕ ತೋರಿಸಿ',
      hideReasoning: 'ತರ್ಕ ಮರೆಮಾಡಿ',
      decisionSupport: 'ಕ್ಲಿನಿಕಲ್ ನಿರ್ಧಾರ ಬೆಂಬಲ',
      actions: 'ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮಗಳು',
      urgency: 'ತುರ್ತು',
      alternatives: 'ಕ್ಲಿನಿಕಲ್ ಟಿಪ್ಪಣಿ',
    },
    timeline: {
      title: 'ರೋಗಿ ಕಾಲಮಾನ ಎಂಜಿನ್',
      subtitle: 'ಕ್ಲಿನಿಕಲ್ ದಾಖಲೆಗಳಿಂದ ರೋಗಿಯ ಇತಿಹಾಸದ ಕಾಲಾನುಕ್ರಮ ಪುನರ್ನಿರ್ಮಾಣ.',
      loadDemo: 'ಡೆಮೊ ಕಾಲಮಾನ ಲೋಡ್ ಮಾಡಿ',
      upload: 'ದಾಖಲೆಗಳು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
      conflicts: 'ಕಾಲ ಸಂಘರ್ಷಗಳು',
      events: 'ಕಾಲಮಾನ ಘಟನೆಗಳು',
      categories: 'ಘಟನೆ ವರ್ಗಗಳು',
    },
    common: {
      analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
      loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
      noData: 'ಡೇಟಾ ಇಲ್ಲ',
      error: 'ದೋಷ ಸಂಭವಿಸಿದೆ',
      demo: 'ಡೆಮೊ ಮೋಡ್',
      synthetic: 'ಸಿಂಥೆಟಿಕ್ ಡೇಟಾ',
      showAll: 'ಎಲ್ಲಾ ತೋರಿಸಿ',
      conflict: 'ಸಂಘರ್ಷಗಳು ಮಾತ್ರ',
    }
  }
}

import React from 'react'
const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en')
  const t = TRANSLATIONS[lang]
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, TRANSLATIONS }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}
